services:
  postgres:
    image: postgres:16
    container_name: dont_be_dumb_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dont_be_dumb
    ports:
      - "5432:5432"
    volumes:
      - dont_be_dumb_pgdata:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:latest
    container_name: dont_be_dumb_metabase
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  dont_be_dumb_pgdata:
